services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - .env
