name: infrastructure
description: Infrastructure for Wiz technical challenge
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
