name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'The environment to deploy to'
        type: environment
      image-tag:
        required: true
        description: 'The image tag to deploy'
        type: string
        default: latest
      update:
        required: true
        description: 'Whether to update the deployment or tear it down'
        type: boolean
        default: true

env:
  sub-dir: deployment

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ inputs.update }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.sub-dir }}/package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - run: npm install
        working-directory: ${{ env.sub-dir }}
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: '${{ vars.DEPLOYMENT_STACK_NAME }}'
          work-dir: ${{ env.sub-dir }}
        env:
          PULUMI_ACCESS_TOKEN: '${{ secrets.PULUMI_ACCESS_TOKEN }}'
          INFRA_STACK_NAME: '${{ vars.INFRA_STACK_NAME }}'
          IMAGE_TAG: '${{ inputs.image-tag }}'
          MONGO_ADMIN_PASSWORD: '${{ secrets.MONGO_ADMIN_PASSWORD }}'
          SECRET_KEY: '${{ secrets.SECRET_KEY }}'

  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ !inputs.update }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.sub-dir }}/package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - run: npm install
        working-directory: ${{ env.sub-dir }}
      - uses: pulumi/actions@v6
        with:
          command: destroy
          stack-name: '${{ vars.DEPLOYMENT_STACK_NAME }}'
          work-dir: ${{ env.sub-dir }}
        env:
          PULUMI_ACCESS_TOKEN: '${{ secrets.PULUMI_ACCESS_TOKEN }}'
