name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'The environment to deploy to'
        type: environment
      image-tag:
        required: true
        description: 'The image tag to deploy'
        type: string
        default: latest

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: deployment/package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
        working-directory: deployment
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: '${{ vars.STACK_NAME }}'
          work-dir: ./deployment
        env:
          PULUMI_ACCESS_TOKEN: '${{ secrets.PULUMI_ACCESS_TOKEN }}'
          STACK_NAME: '${{ vars.STACK_NAME }}'
          IMAGE_TAG: '${{ inputs.image-tag }}'
          MONGO_ADMIN_PASSWORD: '${{ secrets.MONGO_ADMIN_PASSWORD }}'
          SECRET_KEY: '${{ secrets.SECRET_KEY }}'

