name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'The environment to deploy to'
        type: environment
      update:
        required: true
        description: 'Whether to update the infrastructure or tear it down'
        type: boolean
        default: true

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ inputs.update }}
    steps:
      - uses: ./.github/workflows/setup.yaml@main
        with:
          work-dir: infrastructure
          environment: ${{ inputs.environment }}
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ vars.INFRA_STACK_NAME }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ADMIN_PASSWORD: '${{ secrets.MONGO_ADMIN_PASSWORD }}'
          PUBLIC_KEY: '${{ secrets.PUBLIC_KEY }}'

  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ !inputs.update }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: ./.github/workflows/setup.yaml@main
        with:
          work-dir: infrastructure
          environment: ${{ inputs.environment }}
      - uses: pulumi/actions@v6
        with:
          command: destroy
          stack-name: ${{ vars.INFRA_STACK_NAME }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}