name: Setup

on:
  workflow_dispatch:
    inputs:
      work-dir:
        required: true
        description: 'The sub-work-dir to run the setup for'
        type: string
      environment:
        required: true
        description: 'The target aws environment'
        type: environment

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.work-dir }}/package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - run: npm install
        working-directory: ${{ inputs.work-dir }}
